#!/bin/sh

DOTFILES_PATH="$HOME/code/dotfiles"
setup_symlinks() {
  for source in `find ${DOTFILES_PATH} -iname "*.symlink"`
  do
    dest="$HOME/.`basename \"${source%.*}\"`"
    rm -rf $dest
    ln -s $source $dest
  done

  rm -rf $HOME/.config/nvim
  ln -s ${DOTFILES_PATH}/nvim $HOME/.config/nvim
  ln -s ${DOTFILES_PATH}/nvim/ $HOME/.vim
  ln -s ${DOTFILES_PATH}/alacritty/config.yml $HOME/.config/alacritty/alacritty.yml

  echo "symlinks ✓"
}

setup_symlinks
